services:
  calendarDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: calendarDB
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_USER = ${DB_USERNAME}
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${LOCAL_PORT}:1433